"""empty message

Revision ID: 25b8bf1d7803
Revises: 
Create Date: 2020-11-27 15:19:03.550772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b8bf1d7803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_api_operation_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False, comment='日志流水号'),
    sa.Column('user_name', sa.String(length=20), nullable=True, comment='用户名称'),
    sa.Column('operation', sa.String(length=10), nullable=False, comment='操作'),
    sa.Column('object_type', sa.String(length=20), nullable=True, comment='操作对象类型'),
    sa.Column('object_id', sa.String(length=20), nullable=True, comment='操作对象id'),
    sa.Column('info', sa.String(length=50), nullable=True, comment='信息'),
    sa.Column('user_ip', sa.String(length=20), nullable=True, comment='用户ip'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='后台api操作日志表'
    )
    op.create_index(op.f('ix_admin_api_operation_log_create_robot'), 'admin_api_operation_log', ['create_robot'], unique=False)
    op.create_index(op.f('ix_admin_api_operation_log_created_at'), 'admin_api_operation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_api_operation_log_created_by'), 'admin_api_operation_log', ['created_by'], unique=False)
    op.create_table('admin_operation_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False, comment='日志流水号'),
    sa.Column('user_name', sa.String(length=20), nullable=True, comment='用户名称'),
    sa.Column('operation', sa.String(length=10), nullable=False, comment='操作'),
    sa.Column('object_type', sa.String(length=20), nullable=True, comment='操作对象类型'),
    sa.Column('object_id', sa.String(length=20), nullable=True, comment='操作对象id'),
    sa.Column('info', sa.String(length=50), nullable=True, comment='信息'),
    sa.Column('user_ip', sa.String(length=20), nullable=True, comment='用户ip'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='后台用户操作日志表'
    )
    op.create_index(op.f('ix_admin_operation_log_create_robot'), 'admin_operation_log', ['create_robot'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_created_at'), 'admin_operation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_created_by'), 'admin_operation_log', ['created_by'], unique=False)
    op.create_table('dat_company',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False, comment='企业id'),
    sa.Column('company_name', sa.String(length=150), nullable=False, comment='企业名称'),
    sa.Column('tax_number', sa.String(length=18), nullable=False, comment='企业税号'),
    sa.Column('taxpayer_identification_id', sa.Integer(), nullable=False, comment='纳税人资格认定类型id'),
    sa.Column('head_office', sa.Integer(), nullable=False, comment='总机构所在地'),
    sa.Column('province_id', sa.Integer(), nullable=False, comment='省份id'),
    sa.Column('login_way', sa.String(length=30), nullable=False, comment='登录方式'),
    sa.Column('login_account', sa.String(length=20), nullable=True, comment='登录账号'),
    sa.Column('login_password', sa.String(length=256), nullable=True, comment='登录密码(加密)'),
    sa.Column('natural_person_name', sa.String(length=20), nullable=True, comment='自然人姓名'),
    sa.Column('natural_person_ID', sa.String(length=18), nullable=True, comment='自然人身份证号'),
    sa.Column('natural_person_password', sa.String(length=256), nullable=True, comment='自然人登录密码(加密)'),
    sa.Column('taxpayer_name', sa.String(length=20), nullable=True, comment='报税人名称'),
    sa.Column('taxpayer_ID', sa.String(length=18), nullable=True, comment='报税人身份证号'),
    sa.Column('taxpayer_telephone', sa.String(length=20), nullable=True, comment='报税人手机号'),
    sa.Column('valid_start_date', sa.DateTime(timezone=True), nullable=False, comment='有效期开始日期'),
    sa.Column('valid_end_date', sa.DateTime(timezone=True), nullable=False, comment='有效期结束日期'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('ip', sa.String(length=20), nullable=False, comment='ip'),
    sa.Column('company_state', sa.String(length=10), nullable=False, comment='企业状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('tax_number'),
    comment='企业基本信息表'
    )
    op.create_index(op.f('ix_dat_company_company_name'), 'dat_company', ['company_name'], unique=True)
    op.create_index(op.f('ix_dat_company_create_robot'), 'dat_company', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_company_created_at'), 'dat_company', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_company_created_by'), 'dat_company', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_company_update_robot'), 'dat_company', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_company_updated_at'), 'dat_company', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_company_updated_by'), 'dat_company', ['updated_by'], unique=False)
    op.create_table('dat_company_interface',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('company_interface_id', sa.Integer(), autoincrement=True, nullable=False, comment='公司接口配置id'),
    sa.Column('interface_id', sa.Integer(), nullable=False, comment='接口id'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='公司id'),
    sa.Column('state', sa.String(length=10), nullable=False, comment='配置状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('company_interface_id'),
    comment='公司接口配置表'
    )
    op.create_index(op.f('ix_dat_company_interface_create_robot'), 'dat_company_interface', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_company_interface_created_at'), 'dat_company_interface', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_company_interface_created_by'), 'dat_company_interface', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_company_interface_update_robot'), 'dat_company_interface', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_company_interface_updated_at'), 'dat_company_interface', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_company_interface_updated_by'), 'dat_company_interface', ['updated_by'], unique=False)
    op.create_table('dat_company_tax',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('company_tax_id', sa.Integer(), autoincrement=True, nullable=False, comment='企业税种配置id'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企业id'),
    sa.Column('tax_id', sa.Integer(), nullable=False, comment='税种id'),
    sa.Column('frequency', sa.String(length=20), nullable=True, comment='申报频率'),
    sa.Column('ip', sa.String(length=20), nullable=False, comment='ip'),
    sa.Column('company_tax_state', sa.String(length=10), nullable=False, comment='企业税种状态'),
    sa.Column('not_valid_before', sa.DateTime(timezone=True), nullable=True, comment='有效期起'),
    sa.Column('not_valid_after', sa.DateTime(timezone=True), nullable=True, comment='有效期止'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('company_tax_id'),
    comment='企业税种配置表'
    )
    op.create_index(op.f('ix_dat_company_tax_create_robot'), 'dat_company_tax', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_company_tax_created_at'), 'dat_company_tax', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_company_tax_created_by'), 'dat_company_tax', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_company_tax_update_robot'), 'dat_company_tax', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_company_tax_updated_at'), 'dat_company_tax', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_company_tax_updated_by'), 'dat_company_tax', ['updated_by'], unique=False)
    op.create_table('dat_declaration',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('declaration_id', sa.Integer(), autoincrement=True, nullable=False, comment='申报ID'),
    sa.Column('tax_amount', sa.JSON(), nullable=True, comment='应纳税额'),
    sa.Column('tax_start_date', sa.DateTime(timezone=True), nullable=False, comment='申报指标所属期起'),
    sa.Column('tax_end_date', sa.DateTime(timezone=True), nullable=False, comment='申报指标所属期止'),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True, comment='填表日期'),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=True, comment='申报日期'),
    sa.Column('declare_year', sa.Integer(), nullable=True, comment='申报年限'),
    sa.Column('declare_month_start', sa.Integer(), nullable=True, comment='申报月份不早于'),
    sa.Column('declare_month_end', sa.Integer(), nullable=True, comment='申报月份不晚于'),
    sa.Column('declaration_status', sa.String(length=15), nullable=True, comment='申报状态'),
    sa.Column('is_export_successful', sa.Boolean(), nullable=True, comment='导出是否成功'),
    sa.Column('returns_path', sa.String(length=200), nullable=True, comment='申报表路径'),
    sa.Column('payment_status', sa.String(length=15), nullable=True, comment='缴费状态'),
    sa.Column('tax_id', sa.Integer(), nullable=False, comment='税种id'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企业id'),
    sa.Column('company_tax_id', sa.Integer(), nullable=False, comment='企业申报配置id'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('declaration_id'),
    comment='申报详情表'
    )
    op.create_index(op.f('ix_dat_declaration_create_robot'), 'dat_declaration', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_declaration_created_at'), 'dat_declaration', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_declaration_created_by'), 'dat_declaration', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_declaration_update_robot'), 'dat_declaration', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_declaration_updated_at'), 'dat_declaration', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_declaration_updated_by'), 'dat_declaration', ['updated_by'], unique=False)
    op.create_table('dat_declaration_data',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('declaration_data_id', sa.Integer(), autoincrement=True, nullable=False, comment='申报数据id'),
    sa.Column('declaration_data', sa.JSON(), nullable=False, comment='申报数据'),
    sa.Column('declaration_id', sa.Integer(), nullable=False, comment='申报id'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.PrimaryKeyConstraint('declaration_data_id'),
    comment='申报数据'
    )
    op.create_index(op.f('ix_dat_declaration_data_create_robot'), 'dat_declaration_data', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_declaration_data_created_at'), 'dat_declaration_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_declaration_data_created_by'), 'dat_declaration_data', ['created_by'], unique=False)
    op.create_table('dat_interface',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('interface_id', sa.Integer(), autoincrement=True, nullable=False, comment='接口id'),
    sa.Column('interface_name', sa.String(length=20), nullable=False, comment='接口名'),
    sa.Column('interface_description', sa.String(length=50), nullable=True, comment='接口描述'),
    sa.Column('orgid', sa.String(length=50), nullable=True, comment='接口生成的唯一id'),
    sa.Column('accounting_standards', sa.String(length=20), nullable=False, comment='会计准则'),
    sa.Column('tax_code', sa.String(length=20), nullable=False, comment='税种代码'),
    sa.Column('access_type', sa.String(length=10), nullable=False, comment='税种获取方式'),
    sa.Column('can_change', sa.String(length=10), nullable=False, comment='修改纳税人性质'),
    sa.Column('is_return_value', sa.String(length=10), nullable=False),
    sa.Column('extra_info', sa.BLOB(), nullable=True, comment='额外配置信息'),
    sa.Column('interface_state', sa.String(length=20), nullable=False, comment='接口状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('interface_id'),
    comment='接口信息表'
    )
    op.create_index(op.f('ix_dat_interface_create_robot'), 'dat_interface', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_interface_created_at'), 'dat_interface', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_interface_created_by'), 'dat_interface', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_interface_update_robot'), 'dat_interface', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_interface_updated_at'), 'dat_interface', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_interface_updated_by'), 'dat_interface', ['updated_by'], unique=False)
    op.create_table('dat_robot',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('robot_id', sa.Integer(), autoincrement=True, nullable=False, comment='机器人id'),
    sa.Column('robot_name', sa.String(length=20), nullable=False, comment='机器人名'),
    sa.Column('robot_description', sa.String(length=150), nullable=True, comment='机器人描述'),
    sa.Column('computer_name', sa.String(length=20), nullable=False, comment='机器人电脑'),
    sa.Column('robot_secret', sa.String(length=256), nullable=False, comment='机器人密钥（加密）'),
    sa.Column('robot_state', sa.String(length=10), nullable=False, comment='机器人状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('robot_id'),
    sa.UniqueConstraint('robot_name'),
    comment='申报机器人'
    )
    op.create_index(op.f('ix_dat_robot_create_robot'), 'dat_robot', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_robot_created_at'), 'dat_robot', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_robot_created_by'), 'dat_robot', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_robot_update_robot'), 'dat_robot', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_robot_updated_at'), 'dat_robot', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_robot_updated_by'), 'dat_robot', ['updated_by'], unique=False)
    op.create_table('dat_robot_company',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('robot_company_id', sa.Integer(), autoincrement=True, nullable=False, comment='机器人公司配置id'),
    sa.Column('robot_id', sa.Integer(), nullable=False, comment='机器人id'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='公司id'),
    sa.Column('config_state', sa.String(length=10), nullable=False, comment='配置状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('robot_company_id'),
    comment='机器人公司配置'
    )
    op.create_index(op.f('ix_dat_robot_company_create_robot'), 'dat_robot_company', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_robot_company_created_at'), 'dat_robot_company', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_robot_company_created_by'), 'dat_robot_company', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_robot_company_update_robot'), 'dat_robot_company', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_robot_company_updated_at'), 'dat_robot_company', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_robot_company_updated_by'), 'dat_robot_company', ['updated_by'], unique=False)
    op.create_table('dat_role_permission',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('role_permission_id', sa.Integer(), autoincrement=True, nullable=False, comment='角色权限配置id'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色id'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限id'),
    sa.Column('role_permission_state', sa.Boolean(), nullable=False, comment='是否允许'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('role_permission_id'),
    comment='角色权限配置表'
    )
    op.create_index(op.f('ix_dat_role_permission_create_robot'), 'dat_role_permission', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_role_permission_created_at'), 'dat_role_permission', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_role_permission_created_by'), 'dat_role_permission', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_role_permission_update_robot'), 'dat_role_permission', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_role_permission_updated_at'), 'dat_role_permission', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_role_permission_updated_by'), 'dat_role_permission', ['updated_by'], unique=False)
    op.create_table('robot_api_operation_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False, comment='日志流水号'),
    sa.Column('user_name', sa.String(length=20), nullable=True, comment='用户名称'),
    sa.Column('operation', sa.String(length=10), nullable=False, comment='操作'),
    sa.Column('object_type', sa.String(length=20), nullable=True, comment='操作对象类型'),
    sa.Column('object_id', sa.String(length=20), nullable=True, comment='操作对象id'),
    sa.Column('info', sa.String(length=50), nullable=True, comment='信息'),
    sa.Column('user_ip', sa.String(length=20), nullable=True, comment='用户ip'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='机器人api操作日志表'
    )
    op.create_index(op.f('ix_robot_api_operation_log_create_robot'), 'robot_api_operation_log', ['create_robot'], unique=False)
    op.create_index(op.f('ix_robot_api_operation_log_created_at'), 'robot_api_operation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_robot_api_operation_log_created_by'), 'robot_api_operation_log', ['created_by'], unique=False)
    op.create_table('sys_permission',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False, comment='权限id'),
    sa.Column('permission_name', sa.String(length=20), nullable=False, comment='权限名称'),
    sa.Column('permission_description', sa.String(length=50), nullable=True, comment='权限描述'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name'),
    comment='权限表'
    )
    op.create_index(op.f('ix_sys_permission_create_robot'), 'sys_permission', ['create_robot'], unique=False)
    op.create_index(op.f('ix_sys_permission_created_at'), 'sys_permission', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_permission_created_by'), 'sys_permission', ['created_by'], unique=False)
    op.create_index(op.f('ix_sys_permission_update_robot'), 'sys_permission', ['update_robot'], unique=False)
    op.create_index(op.f('ix_sys_permission_updated_at'), 'sys_permission', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sys_permission_updated_by'), 'sys_permission', ['updated_by'], unique=False)
    op.create_table('sys_province',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('province_id', sa.Integer(), autoincrement=True, nullable=False, comment='省份id'),
    sa.Column('province_name', sa.String(length=20), nullable=False, comment='省份名称'),
    sa.Column('province_code', sa.String(length=10), nullable=True, comment='省份代码'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('province_id'),
    sa.UniqueConstraint('province_name'),
    comment='省份表'
    )
    op.create_index(op.f('ix_sys_province_create_robot'), 'sys_province', ['create_robot'], unique=False)
    op.create_index(op.f('ix_sys_province_created_at'), 'sys_province', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_province_created_by'), 'sys_province', ['created_by'], unique=False)
    op.create_index(op.f('ix_sys_province_update_robot'), 'sys_province', ['update_robot'], unique=False)
    op.create_index(op.f('ix_sys_province_updated_at'), 'sys_province', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sys_province_updated_by'), 'sys_province', ['updated_by'], unique=False)
    op.create_table('sys_role',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False, comment='角色id'),
    sa.Column('role_name', sa.String(length=20), nullable=False, comment='角色名称'),
    sa.Column('role_description', sa.String(length=50), nullable=True, comment='角色描述'),
    sa.Column('role_state', sa.String(length=10), nullable=False, comment='角色状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name'),
    comment='角色表'
    )
    op.create_index(op.f('ix_sys_role_create_robot'), 'sys_role', ['create_robot'], unique=False)
    op.create_index(op.f('ix_sys_role_created_at'), 'sys_role', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_role_created_by'), 'sys_role', ['created_by'], unique=False)
    op.create_index(op.f('ix_sys_role_update_robot'), 'sys_role', ['update_robot'], unique=False)
    op.create_index(op.f('ix_sys_role_updated_at'), 'sys_role', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sys_role_updated_by'), 'sys_role', ['updated_by'], unique=False)
    op.create_table('sys_tax_type',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('tax_id', sa.Integer(), autoincrement=True, nullable=False, comment='税种id'),
    sa.Column('tax_name', sa.String(length=40), nullable=False, comment='税种名称(英文)，对应接口路由'),
    sa.Column('tax_name_cn', sa.String(length=40), nullable=False, comment='税种名称(中文)'),
    sa.Column('tax_code', sa.String(length=20), nullable=False, comment='税种代码'),
    sa.Column('tax_type', sa.String(length=20), nullable=True, comment='税种类型'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('tax_id'),
    sa.UniqueConstraint('tax_name'),
    sa.UniqueConstraint('tax_name_cn'),
    comment='申报税种表'
    )
    op.create_index(op.f('ix_sys_tax_type_create_robot'), 'sys_tax_type', ['create_robot'], unique=False)
    op.create_index(op.f('ix_sys_tax_type_created_at'), 'sys_tax_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_tax_type_created_by'), 'sys_tax_type', ['created_by'], unique=False)
    op.create_index(op.f('ix_sys_tax_type_tax_code'), 'sys_tax_type', ['tax_code'], unique=False)
    op.create_index(op.f('ix_sys_tax_type_update_robot'), 'sys_tax_type', ['update_robot'], unique=False)
    op.create_index(op.f('ix_sys_tax_type_updated_at'), 'sys_tax_type', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sys_tax_type_updated_by'), 'sys_tax_type', ['updated_by'], unique=False)
    op.create_table('sys_taxpayer_identification',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('taxpayer_identification_id', sa.Integer(), autoincrement=True, nullable=False, comment='纳税人资格认定类型id'),
    sa.Column('taxpayer_identification_name', sa.String(length=20), nullable=False, comment='纳税人资格认定类型名'),
    sa.Column('taxpayer_identification_code', sa.String(length=20), nullable=False, comment='纳税人资格认定代码'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('taxpayer_identification_id'),
    sa.UniqueConstraint('taxpayer_identification_code'),
    sa.UniqueConstraint('taxpayer_identification_name'),
    comment='纳税人资格认定类型表'
    )
    op.create_index(op.f('ix_sys_taxpayer_identification_create_robot'), 'sys_taxpayer_identification', ['create_robot'], unique=False)
    op.create_index(op.f('ix_sys_taxpayer_identification_created_at'), 'sys_taxpayer_identification', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_taxpayer_identification_created_by'), 'sys_taxpayer_identification', ['created_by'], unique=False)
    op.create_index(op.f('ix_sys_taxpayer_identification_update_robot'), 'sys_taxpayer_identification', ['update_robot'], unique=False)
    op.create_index(op.f('ix_sys_taxpayer_identification_updated_at'), 'sys_taxpayer_identification', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sys_taxpayer_identification_updated_by'), 'sys_taxpayer_identification', ['updated_by'], unique=False)
    op.create_table('sys_user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('user_name', sa.String(length=20), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='用户密码（加密）'),
    sa.Column('contact_person', sa.String(length=20), nullable=False, comment='联系人'),
    sa.Column('address', sa.String(length=50), nullable=False, comment='联系地址'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='邮箱地址'),
    sa.Column('telephone', sa.String(length=20), nullable=False, comment='电话号码'),
    sa.Column('ip', sa.String(length=20), nullable=False, comment='注册时的ip'),
    sa.Column('user_state', sa.String(length=20), nullable=False, comment='用户状态'),
    sa.Column('api_key', sa.String(length=32), nullable=False, comment='接口id'),
    sa.Column('secret_key', sa.String(length=256), nullable=False, comment='接口密钥(加密)'),
    sa.Column('api_state', sa.String(length=10), nullable=False, comment='接口状态'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='用户角色'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone'),
    comment='用户表'
    )
    op.create_index(op.f('ix_sys_user_api_key'), 'sys_user', ['api_key'], unique=False)
    op.create_index(op.f('ix_sys_user_create_robot'), 'sys_user', ['create_robot'], unique=False)
    op.create_index(op.f('ix_sys_user_created_at'), 'sys_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_user_created_by'), 'sys_user', ['created_by'], unique=False)
    op.create_index(op.f('ix_sys_user_update_robot'), 'sys_user', ['update_robot'], unique=False)
    op.create_index(op.f('ix_sys_user_updated_at'), 'sys_user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sys_user_updated_by'), 'sys_user', ['updated_by'], unique=False)
    op.create_table('u_api_operation_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False, comment='日志流水号'),
    sa.Column('user_name', sa.String(length=20), nullable=True, comment='用户名称'),
    sa.Column('operation', sa.String(length=10), nullable=False, comment='操作'),
    sa.Column('object_type', sa.String(length=20), nullable=True, comment='操作对象类型'),
    sa.Column('object_id', sa.String(length=20), nullable=True, comment='操作对象id'),
    sa.Column('info', sa.String(length=50), nullable=True, comment='信息'),
    sa.Column('user_ip', sa.String(length=20), nullable=True, comment='用户ip'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='api操作日志表'
    )
    op.create_index(op.f('ix_u_api_operation_log_create_robot'), 'u_api_operation_log', ['create_robot'], unique=False)
    op.create_index(op.f('ix_u_api_operation_log_created_at'), 'u_api_operation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_u_api_operation_log_created_by'), 'u_api_operation_log', ['created_by'], unique=False)
    op.create_table('u_operation_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False, comment='日志流水号'),
    sa.Column('user_name', sa.String(length=20), nullable=True, comment='用户名称'),
    sa.Column('operation', sa.String(length=10), nullable=False, comment='操作'),
    sa.Column('object_type', sa.String(length=20), nullable=True, comment='操作对象类型'),
    sa.Column('object_id', sa.String(length=20), nullable=True, comment='操作对象id'),
    sa.Column('info', sa.String(length=50), nullable=True, comment='信息'),
    sa.Column('user_ip', sa.String(length=20), nullable=True, comment='用户ip'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='用户操作日志表'
    )
    op.create_index(op.f('ix_u_operation_log_create_robot'), 'u_operation_log', ['create_robot'], unique=False)
    op.create_index(op.f('ix_u_operation_log_created_at'), 'u_operation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_u_operation_log_created_by'), 'u_operation_log', ['created_by'], unique=False)
    # ### end Alembic commands ###
    op.execute('insert into sys_role (role_name, role_state, created_by) values ("administrator", "active", 0);')
    op.execute('insert into sys_role (role_name, role_state, created_by) values ("customer", "active", 0);')
    for code, name in [
        (11, '北京市'),
        (12, '天津市'),
        (13, '河北省'),
        (14, '山西省'),
        (15, '内蒙古区'),
        (21, '辽宁省'),
        (22, '吉林省'),
        (23, '黑龙江省'),
        (31, '上海市'),
        (32, '江苏省'),
        (33, '浙江省'),
        (34, '安徽省'),
        (35, '福建省'),
        (36, '江西省'),
        (37, '山东省'),
        (41, '河南省'),
        (42, '湖北省'),
        (43, '湖南省'),
        (44, '广东省'),
        (45, '广西区'),
        (46, '海南省'),
        (50, '重庆市'),
        (51, '四川省'),
        (52, '贵州省'),
        (53, '云南省'),
        (54, '西藏区'),
        (61, '陕西省'),
        (62, '甘肃省'),
        (63, '青海省'),
        (64, '宁夏区'),
        (65, '新疆区'),
        (2102, '大连市'),
        (3302, '宁波市'),
        (3502, '厦门市'),
        (3702, '青岛市'),
        (4403, '深圳市')
    ]:
        op.execute(
            f'insert into sys_province (province_code, province_name, created_by) values ({code}, "{name}", 0); ')
    for name, code in [('一般纳税人', '2000010001'), ('小规模纳税人', '2000010002')]:
        op.execute(
            f'insert into sys_taxpayer_identification (taxpayer_identification_name, taxpayer_identification_code, created_by) values ("{name}", "{code}", 0);')
    for tax_name, tax_name_cn, tax_code in [
        ('enterprise-income', '企业所得税月(季)报A类', '10412'),
        ('VAT-small-scale', '增值税小规模纳税人', '10102'),
        ('financial-statement-new-financial', '财务报表(已执行新金融)', 'B9806'),
        ('VAT', '增值税一般纳税人', '10101'),
        ('additional', '城建税、教育费附加、地方教育附加税(月、季)(费)', '10516'),
        ('disability-protection', '残疾人保障基金', '10517'),
        ('stamp-month', '印花税（月）', '10111'),
        ('stamp-count', '印花税（次）', 'B0111'),
        ('union-fund', '工会申报表', '30598'),
        ('water-conservancy', '水利申报表', '30599'),
        ('financial-statement-ASBE', '财务报表(企业会计制度)', '39805'),
        ('financial-statement-FRSSE', '财务报表(小企业会计准则)', '29806'),
        ('financial-statement-general', '财务报表(已执行一般)', 'B9807'),

    ]:
        op.execute(
            f"insert into sys_tax_type (tax_name,tax_name_cn,tax_code,created_by)values('{tax_name}','{tax_name_cn}','{tax_code}',0);")
    op.execute(
        'insert into sys_user (user_name, password, contact_person, address, email, telephone, ip, user_state, api_state, role_id, created_by, api_key, secret_key) '
        'values ("developer", "pbkdf2:sha256:150000$LTftI2ji$d779c6395537a45e5ae696ec1c28ef8c50ec0a0b2ffc38019b39b6b9d9f15cee", "developer", "北京",'
        ' "developer@tzcpa.com", "1234567", "127.0.0.1", "active", "active", 1, 0, "10162afcc69f36ec94bebb560fe2bd5f", '
        '"6f0c26f1200cefb2797030dc03b6063f57dc6499c5504b76105ed65ff11bbaf4c1a275c6309b7b19594b584dc29a91617d8cae9868a4e93adf11f68d3822bba12f9e811d5abd2fe9d1db6f829929e0c6e7b8225ed3b59c29c47efefec81ff51bbfb34f33d08fd4127bcfc386423d73de5d8f1384e8619d89b2271379635fbe52");')
    op.execute(
        'insert into dat_company (company_name, company_state, tax_number, taxpayer_identification_id, province_id,head_office, login_way,valid_start_date,valid_end_date,user_id,ip,created_by) values '
        '("测试专用公司勿删", "active", "XXXXXXXXXXXXXXXXX", 1,1,1,"real_name","2020-01-01","2999-01-01",1,"127.0.0.1",1)')
    op.execute(
        'insert into dat_robot (computer_name, robot_name, robot_secret, robot_state, created_by) values '
        '("计算机1", "测试专用机器人勿删", "13e75650c7cab9dd675e7aa8a63a43afc438c8826cbffcf51dad83a96f2f279e31a3df42f45f9c7b5a0ba20e83323727014cd98e48a8d53def9d28f9cf376f31fbfde3a699c7fa4104a7fb898452d197e16a64016947fdb5bc6b45c6936863bb1fca99ed2ac6ca8f22f46dc8e71e01efa54bda4bffa1e1cda2f9a83076f93817", "active", 1)')
    for tax_id, frequency in [
        (1, 'half_year'), (2, 'quarter'), (3, 'year'), (4, 'month'), (5, 'month'), (6, 'month'), (7, 'month'),
        (8, 'month'),
        (9, 'month'), (10, 'month'), (11, 'month'), (12, 'month'), (13, 'month'),
    ]:
        op.execute(
            f'insert into dat_company_tax (company_id, tax_id, frequency, ip, company_tax_state, created_by) values (1, {tax_id}, "{frequency}", "127.0.0.1", "active", 1);')
    op.execute(
        'insert into dat_robot_company (robot_id, company_id, config_state, created_by) values (1, 1, "active", 1)')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_operation_log_created_by'), table_name='u_operation_log')
    op.drop_index(op.f('ix_u_operation_log_created_at'), table_name='u_operation_log')
    op.drop_index(op.f('ix_u_operation_log_create_robot'), table_name='u_operation_log')
    op.drop_table('u_operation_log')
    op.drop_index(op.f('ix_u_api_operation_log_created_by'), table_name='u_api_operation_log')
    op.drop_index(op.f('ix_u_api_operation_log_created_at'), table_name='u_api_operation_log')
    op.drop_index(op.f('ix_u_api_operation_log_create_robot'), table_name='u_api_operation_log')
    op.drop_table('u_api_operation_log')
    op.drop_index(op.f('ix_sys_user_updated_by'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_updated_at'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_update_robot'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_created_by'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_created_at'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_create_robot'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_api_key'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_taxpayer_identification_updated_by'), table_name='sys_taxpayer_identification')
    op.drop_index(op.f('ix_sys_taxpayer_identification_updated_at'), table_name='sys_taxpayer_identification')
    op.drop_index(op.f('ix_sys_taxpayer_identification_update_robot'), table_name='sys_taxpayer_identification')
    op.drop_index(op.f('ix_sys_taxpayer_identification_created_by'), table_name='sys_taxpayer_identification')
    op.drop_index(op.f('ix_sys_taxpayer_identification_created_at'), table_name='sys_taxpayer_identification')
    op.drop_index(op.f('ix_sys_taxpayer_identification_create_robot'), table_name='sys_taxpayer_identification')
    op.drop_table('sys_taxpayer_identification')
    op.drop_index(op.f('ix_sys_tax_type_updated_by'), table_name='sys_tax_type')
    op.drop_index(op.f('ix_sys_tax_type_updated_at'), table_name='sys_tax_type')
    op.drop_index(op.f('ix_sys_tax_type_update_robot'), table_name='sys_tax_type')
    op.drop_index(op.f('ix_sys_tax_type_tax_code'), table_name='sys_tax_type')
    op.drop_index(op.f('ix_sys_tax_type_created_by'), table_name='sys_tax_type')
    op.drop_index(op.f('ix_sys_tax_type_created_at'), table_name='sys_tax_type')
    op.drop_index(op.f('ix_sys_tax_type_create_robot'), table_name='sys_tax_type')
    op.drop_table('sys_tax_type')
    op.drop_index(op.f('ix_sys_role_updated_by'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_updated_at'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_update_robot'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_created_by'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_created_at'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_create_robot'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_province_updated_by'), table_name='sys_province')
    op.drop_index(op.f('ix_sys_province_updated_at'), table_name='sys_province')
    op.drop_index(op.f('ix_sys_province_update_robot'), table_name='sys_province')
    op.drop_index(op.f('ix_sys_province_created_by'), table_name='sys_province')
    op.drop_index(op.f('ix_sys_province_created_at'), table_name='sys_province')
    op.drop_index(op.f('ix_sys_province_create_robot'), table_name='sys_province')
    op.drop_table('sys_province')
    op.drop_index(op.f('ix_sys_permission_updated_by'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_updated_at'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_update_robot'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_created_by'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_created_at'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_create_robot'), table_name='sys_permission')
    op.drop_table('sys_permission')
    op.drop_index(op.f('ix_robot_api_operation_log_created_by'), table_name='robot_api_operation_log')
    op.drop_index(op.f('ix_robot_api_operation_log_created_at'), table_name='robot_api_operation_log')
    op.drop_index(op.f('ix_robot_api_operation_log_create_robot'), table_name='robot_api_operation_log')
    op.drop_table('robot_api_operation_log')
    op.drop_index(op.f('ix_dat_role_permission_updated_by'), table_name='dat_role_permission')
    op.drop_index(op.f('ix_dat_role_permission_updated_at'), table_name='dat_role_permission')
    op.drop_index(op.f('ix_dat_role_permission_update_robot'), table_name='dat_role_permission')
    op.drop_index(op.f('ix_dat_role_permission_created_by'), table_name='dat_role_permission')
    op.drop_index(op.f('ix_dat_role_permission_created_at'), table_name='dat_role_permission')
    op.drop_index(op.f('ix_dat_role_permission_create_robot'), table_name='dat_role_permission')
    op.drop_table('dat_role_permission')
    op.drop_index(op.f('ix_dat_robot_company_updated_by'), table_name='dat_robot_company')
    op.drop_index(op.f('ix_dat_robot_company_updated_at'), table_name='dat_robot_company')
    op.drop_index(op.f('ix_dat_robot_company_update_robot'), table_name='dat_robot_company')
    op.drop_index(op.f('ix_dat_robot_company_created_by'), table_name='dat_robot_company')
    op.drop_index(op.f('ix_dat_robot_company_created_at'), table_name='dat_robot_company')
    op.drop_index(op.f('ix_dat_robot_company_create_robot'), table_name='dat_robot_company')
    op.drop_table('dat_robot_company')
    op.drop_index(op.f('ix_dat_robot_updated_by'), table_name='dat_robot')
    op.drop_index(op.f('ix_dat_robot_updated_at'), table_name='dat_robot')
    op.drop_index(op.f('ix_dat_robot_update_robot'), table_name='dat_robot')
    op.drop_index(op.f('ix_dat_robot_created_by'), table_name='dat_robot')
    op.drop_index(op.f('ix_dat_robot_created_at'), table_name='dat_robot')
    op.drop_index(op.f('ix_dat_robot_create_robot'), table_name='dat_robot')
    op.drop_table('dat_robot')
    op.drop_index(op.f('ix_dat_interface_updated_by'), table_name='dat_interface')
    op.drop_index(op.f('ix_dat_interface_updated_at'), table_name='dat_interface')
    op.drop_index(op.f('ix_dat_interface_update_robot'), table_name='dat_interface')
    op.drop_index(op.f('ix_dat_interface_created_by'), table_name='dat_interface')
    op.drop_index(op.f('ix_dat_interface_created_at'), table_name='dat_interface')
    op.drop_index(op.f('ix_dat_interface_create_robot'), table_name='dat_interface')
    op.drop_table('dat_interface')
    op.drop_index(op.f('ix_dat_declaration_data_created_by'), table_name='dat_declaration_data')
    op.drop_index(op.f('ix_dat_declaration_data_created_at'), table_name='dat_declaration_data')
    op.drop_index(op.f('ix_dat_declaration_data_create_robot'), table_name='dat_declaration_data')
    op.drop_table('dat_declaration_data')
    op.drop_index(op.f('ix_dat_declaration_updated_by'), table_name='dat_declaration')
    op.drop_index(op.f('ix_dat_declaration_updated_at'), table_name='dat_declaration')
    op.drop_index(op.f('ix_dat_declaration_update_robot'), table_name='dat_declaration')
    op.drop_index(op.f('ix_dat_declaration_created_by'), table_name='dat_declaration')
    op.drop_index(op.f('ix_dat_declaration_created_at'), table_name='dat_declaration')
    op.drop_index(op.f('ix_dat_declaration_create_robot'), table_name='dat_declaration')
    op.drop_table('dat_declaration')
    op.drop_index(op.f('ix_dat_company_tax_updated_by'), table_name='dat_company_tax')
    op.drop_index(op.f('ix_dat_company_tax_updated_at'), table_name='dat_company_tax')
    op.drop_index(op.f('ix_dat_company_tax_update_robot'), table_name='dat_company_tax')
    op.drop_index(op.f('ix_dat_company_tax_created_by'), table_name='dat_company_tax')
    op.drop_index(op.f('ix_dat_company_tax_created_at'), table_name='dat_company_tax')
    op.drop_index(op.f('ix_dat_company_tax_create_robot'), table_name='dat_company_tax')
    op.drop_table('dat_company_tax')
    op.drop_index(op.f('ix_dat_company_interface_updated_by'), table_name='dat_company_interface')
    op.drop_index(op.f('ix_dat_company_interface_updated_at'), table_name='dat_company_interface')
    op.drop_index(op.f('ix_dat_company_interface_update_robot'), table_name='dat_company_interface')
    op.drop_index(op.f('ix_dat_company_interface_created_by'), table_name='dat_company_interface')
    op.drop_index(op.f('ix_dat_company_interface_created_at'), table_name='dat_company_interface')
    op.drop_index(op.f('ix_dat_company_interface_create_robot'), table_name='dat_company_interface')
    op.drop_table('dat_company_interface')
    op.drop_index(op.f('ix_dat_company_updated_by'), table_name='dat_company')
    op.drop_index(op.f('ix_dat_company_updated_at'), table_name='dat_company')
    op.drop_index(op.f('ix_dat_company_update_robot'), table_name='dat_company')
    op.drop_index(op.f('ix_dat_company_created_by'), table_name='dat_company')
    op.drop_index(op.f('ix_dat_company_created_at'), table_name='dat_company')
    op.drop_index(op.f('ix_dat_company_create_robot'), table_name='dat_company')
    op.drop_index(op.f('ix_dat_company_company_name'), table_name='dat_company')
    op.drop_table('dat_company')
    op.drop_index(op.f('ix_admin_operation_log_created_by'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_created_at'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_create_robot'), table_name='admin_operation_log')
    op.drop_table('admin_operation_log')
    op.drop_index(op.f('ix_admin_api_operation_log_created_by'), table_name='admin_api_operation_log')
    op.drop_index(op.f('ix_admin_api_operation_log_created_at'), table_name='admin_api_operation_log')
    op.drop_index(op.f('ix_admin_api_operation_log_create_robot'), table_name='admin_api_operation_log')
    op.drop_table('admin_api_operation_log')
    # ### end Alembic commands ###
