"""empty message

Revision ID: 851e7969fe3c
Revises: ce156c5f95ec
Create Date: 2020-12-09 17:11:50.219940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '851e7969fe3c'
down_revision = 'ce156c5f95ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dat_declaration', sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True, comment='申报表导出时间'))
    op.add_column('dat_declaration', sa.Column('returns_expired_at', sa.DateTime(timezone=True), nullable=True, comment='申报表过期时间'))
    op.add_column('dat_tax_clearance_certificate', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True, comment='完税证明过期时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dat_tax_clearance_certificate', 'expired_at')
    op.drop_column('dat_declaration', 'returns_expired_at')
    op.drop_column('dat_declaration', 'exported_at')
    # ### end Alembic commands ###
