"""empty message

Revision ID: a38b0fe4ad18
Revises: 4f8c2ac6e124
Create Date: 2021-01-19 17:39:35.051623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38b0fe4ad18'
down_revision = '4f8c2ac6e124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dat_company', sa.Column('registration_number', sa.String(length=25), nullable=True, comment='登记序号'))
    op.add_column('dat_company', sa.Column('tax_authority_code', sa.String(length=15), nullable=True, comment='税务机关代码'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dat_company', 'tax_authority_code')
    op.drop_column('dat_company', 'registration_number')
    # ### end Alembic commands ###
