"""empty message

Revision ID: b2b0f59d1b20
Revises: 25b8bf1d7803
Create Date: 2020-12-02 14:04:09.496302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2b0f59d1b20'
down_revision = '25b8bf1d7803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dat_company_interface', sa.Column('access_type', sa.String(length=10), nullable=False, comment='税种获取方式'))
    op.add_column('dat_company_interface', sa.Column('accounting_standards', sa.String(length=20), nullable=False, comment='会计准则'))
    op.add_column('dat_company_interface', sa.Column('can_change', sa.String(length=10), nullable=False, comment='修改纳税人性质'))
    op.add_column('dat_company_interface', sa.Column('extra_info', sa.BLOB(), nullable=True, comment='额外配置信息'))
    op.add_column('dat_company_interface', sa.Column('is_return_value', sa.String(length=10), nullable=False))
    op.add_column('dat_company_interface', sa.Column('orgid', sa.String(length=50), nullable=True, comment='接口生成的唯一id'))
    op.add_column('dat_company_interface', sa.Column('tax_code', sa.String(length=20), nullable=False, comment='税种代码'))
    op.alter_column('dat_declaration', 'declare_month_end',
               existing_type=mysql.INTEGER(display_width=11),
               comment='申报月份不晚于',
               existing_nullable=True)
    op.alter_column('dat_declaration', 'declare_month_start',
               existing_type=mysql.INTEGER(display_width=11),
               comment='申报月份不早于',
               existing_nullable=True)
    op.alter_column('dat_declaration', 'declare_year',
               existing_type=mysql.INTEGER(display_width=11),
               comment='申报年限',
               existing_nullable=True)
    op.alter_column('dat_declaration_data', 'declaration_data',
               existing_type=mysql.TEXT(),
               nullable=False,
               comment='申报数据')
    op.drop_column('dat_interface', 'orgid')
    op.drop_column('dat_interface', 'accounting_standards')
    op.drop_column('dat_interface', 'can_change')
    op.drop_column('dat_interface', 'tax_code')
    op.drop_column('dat_interface', 'extra_info')
    op.drop_column('dat_interface', 'is_return_value')
    op.drop_column('dat_interface', 'access_type')
    op.add_column('dat_declaration', sa.Column('declaration_info', sa.JSON(), nullable=True, comment='申报错误信息'))
    # ### end Alembic commands ###
    op.execute("insert into dat_interface (interface_name, interface_state, created_by) values ('金财', 'active', 0);")


def downgrade():
    # ### commands auto generated by Alembic - please adjust!
    op.drop_column('dat_declaration', 'declaration_info')
    op.add_column('dat_interface', sa.Column('access_type', mysql.VARCHAR(length=10), nullable=False, comment='税种获取方式'))
    op.add_column('dat_interface', sa.Column('is_return_value', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('dat_interface', sa.Column('extra_info', sa.BLOB(), nullable=True, comment='额外配置信息'))
    op.add_column('dat_interface', sa.Column('tax_code', mysql.VARCHAR(length=20), nullable=False, comment='税种代码'))
    op.add_column('dat_interface', sa.Column('can_change', mysql.VARCHAR(length=10), nullable=False, comment='修改纳税:w人性质'))
    op.add_column('dat_interface', sa.Column('accounting_standards', mysql.VARCHAR(length=20), nullable=False, comment='会计准则'))
    op.add_column('dat_interface', sa.Column('orgid', mysql.VARCHAR(length=50), nullable=True, comment='接口生成的唯一id'))
    op.alter_column('dat_declaration_data', 'declaration_data',
               existing_type=mysql.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='申报数据')
    op.alter_column('dat_declaration', 'declare_year',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='申报年限',
               existing_nullable=True)
    op.alter_column('dat_declaration', 'declare_month_start',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='申报月份不早于',
               existing_nullable=True)
    op.alter_column('dat_declaration', 'declare_month_end',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='申报月份不晚于',
               existing_nullable=True)
    op.drop_column('dat_company_interface', 'tax_code')
    op.drop_column('dat_company_interface', 'orgid')
    op.drop_column('dat_company_interface', 'is_return_value')
    op.drop_column('dat_company_interface', 'extra_info')
    op.drop_column('dat_company_interface', 'can_change')
    op.drop_column('dat_company_interface', 'accounting_standards')
    op.drop_column('dat_company_interface', 'access_type')
    # ### end Alembic commands ###
