"""empty message

Revision ID: b7e23ef81504
Revises: 851e7969fe3c
Create Date: 2020-12-10 18:11:12.755700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7e23ef81504'
down_revision = '851e7969fe3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dat_declaration', sa.Column('returns_cleared', sa.Boolean(), nullable=True, comment='申报表是否已经清理'))
    op.add_column('dat_tax_clearance_certificate', sa.Column('cleared', sa.Boolean(), nullable=True, comment='完税证明是否已经清理'))
    op.alter_column('dat_tax_clearance_certificate', 'declare_month_end',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='申报月份不晚于')
    op.alter_column('dat_tax_clearance_certificate', 'declare_month_start',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='申报月份不早于')
    op.alter_column('dat_tax_clearance_certificate', 'declare_year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='申报年限')
    op.alter_column('dat_tax_clearance_certificate', 'file_path',
               existing_type=mysql.JSON(),
               nullable=False,
               existing_comment='文件存储位置')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dat_tax_clearance_certificate', 'file_path',
               existing_type=mysql.JSON(),
               nullable=True,
               existing_comment='文件存储位置')
    op.alter_column('dat_tax_clearance_certificate', 'declare_year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='申报年限')
    op.alter_column('dat_tax_clearance_certificate', 'declare_month_start',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='申报月份不早于')
    op.alter_column('dat_tax_clearance_certificate', 'declare_month_end',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='申报月份不晚于')
    op.drop_column('dat_tax_clearance_certificate', 'cleared')
    op.drop_column('dat_declaration', 'returns_cleared')
    # ### end Alembic commands ###
