"""empty message

Revision ID: ce156c5f95ec
Revises: b2b0f59d1b20
Create Date: 2020-12-09 15:19:03.687763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce156c5f95ec'
down_revision = 'b2b0f59d1b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dat_tax_clearance_certificate',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新日期'),
    sa.Column('certificate_id', sa.Integer(), autoincrement=True, nullable=False, comment='完税证明id'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='公司id'),
    sa.Column('declare_year', sa.Integer(), nullable=True, comment='申报年限'),
    sa.Column('declare_month_start', sa.Integer(), nullable=True, comment='申报月份不早于'),
    sa.Column('declare_month_end', sa.Integer(), nullable=True, comment='申报月份不晚于'),
    sa.Column('file_path', sa.JSON(), nullable=True, comment='文件存储位置'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_robot', sa.Integer(), nullable=True, comment='负责创建的机器人'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_robot', sa.Integer(), nullable=True, comment='负责更新的机器人'),
    sa.PrimaryKeyConstraint('certificate_id'),
    comment='完税证明表'
    )
    op.create_index(op.f('ix_dat_tax_clearance_certificate_create_robot'), 'dat_tax_clearance_certificate', ['create_robot'], unique=False)
    op.create_index(op.f('ix_dat_tax_clearance_certificate_created_at'), 'dat_tax_clearance_certificate', ['created_at'], unique=False)
    op.create_index(op.f('ix_dat_tax_clearance_certificate_created_by'), 'dat_tax_clearance_certificate', ['created_by'], unique=False)
    op.create_index(op.f('ix_dat_tax_clearance_certificate_update_robot'), 'dat_tax_clearance_certificate', ['update_robot'], unique=False)
    op.create_index(op.f('ix_dat_tax_clearance_certificate_updated_at'), 'dat_tax_clearance_certificate', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dat_tax_clearance_certificate_updated_by'), 'dat_tax_clearance_certificate', ['updated_by'], unique=False)
    op.alter_column('dat_declaration', 'returns_path',
               type_=mysql.JSON(),
               comment='文件存储位置',
               existing_comment='申报表路径',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dat_declaration', 'returns_path',
               type_=mysql.VARCHAR(length=200),
               comment='申报表路径',
               existing_comment='文件存储位置',
               existing_nullable=True)
    op.drop_index(op.f('ix_dat_tax_clearance_certificate_updated_by'), table_name='dat_tax_clearance_certificate')
    op.drop_index(op.f('ix_dat_tax_clearance_certificate_updated_at'), table_name='dat_tax_clearance_certificate')
    op.drop_index(op.f('ix_dat_tax_clearance_certificate_update_robot'), table_name='dat_tax_clearance_certificate')
    op.drop_index(op.f('ix_dat_tax_clearance_certificate_created_by'), table_name='dat_tax_clearance_certificate')
    op.drop_index(op.f('ix_dat_tax_clearance_certificate_created_at'), table_name='dat_tax_clearance_certificate')
    op.drop_index(op.f('ix_dat_tax_clearance_certificate_create_robot'), table_name='dat_tax_clearance_certificate')
    op.drop_table('dat_tax_clearance_certificate')
    # ### end Alembic commands ###
