"""empty message

Revision ID: ea361e36e741
Revises: a38b0fe4ad18
Create Date: 2021-01-21 10:15:11.851566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea361e36e741'
down_revision = 'a38b0fe4ad18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dat_declaration', sa.Column('offical_tax_amount', sa.JSON(), nullable=True, comment='报税平台上计算出的本期应补退税额'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dat_declaration', 'offical_tax_amount')
    # ### end Alembic commands ###
